<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.micronaut.build.examples</groupId>
        <artifactId>issue1481</artifactId>
        <version>0.1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>module-b</artifactId>

    <packaging>${packaging}</packaging>

    <properties>
        <packaging>jar</packaging>
        <exec.mainClass>org.example.Main</exec.mainClass>
    </properties>

    <profiles>
        <profile>
            <id>arm64</id>
            <activation>
                <property>
                    <name>os.arch</name>
                    <value>aarch64</value>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.google.cloud.tools</groupId>
                        <artifactId>jib-maven-plugin</artifactId>
                        <configuration>
                            <from>
                                <platforms>
                                    <platform>
                                        <architecture>arm64</architecture>
                                        <os>linux</os>
                                    </platform>
                                </platforms>
                            </from>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>io.micronaut.maven</groupId>
                <artifactId>micronaut-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <configuration>
                    <to>
                        <image>docker.io/alvarosanchez/${project.artifactId}:${project.version}</image>
                    </to>
                    <pluginExtensions>
                        <pluginExtension>
                            <implementation>io.micronaut.maven.jib.JibMicronautExtension</implementation>
                        </pluginExtension>
                    </pluginExtensions>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>io.micronaut.maven</groupId>
                        <artifactId>micronaut-maven-jib-integration</artifactId>
                        <version>${micronaut-maven-plugin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <configuration>
                    <showLogs>true</showLogs>
                    <images>
                        <image>
                            <name>alvarosanchez/${project.artifactId}:${project.version}</name>
                            <run>
                                <wait>
                                    <log>Stop</log>
                                    <time>20000</time>
                                </wait>
                            </run>
                        </image>
                    </images>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>io.micronaut.build.examples</groupId>
            <artifactId>module-a</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-context</artifactId>
        </dependency>
    </dependencies>
</project>