invoker.goals = -ntp mn:native-image-jib -Dpackaging=native-image-jib -Djib.buildGoal=buildTar -Dmicronaut.native-image.jib.executable=target/missing-native-image
invoker.buildResult = failure

invoker.os.family = !windows
