invoker.goals = -ntp mn:dockerfile -Dpackaging=docker -Dmicronaut.docker.jdkAotCache=true -Dmicronaut.docker.jdkAotCache.trainingPaths=/hello compile docker:build docker:start docker:stop

invoker.os.family = !windows
