{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.jsonschema",
    "module": "micronaut-json-schema-common",
    "version": "1.5.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "4.8.9"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "micronaut-json-schema-common-1.5.1-SNAPSHOT.jar",
          "url": "micronaut-json-schema-common-1.5.1-SNAPSHOT.jar",
          "size": 16417,
          "sha512": "64c3278bcaad8ede86bb75163b64434352085e3d9df647f5dfcf2c873ef53474a8a4158fabc89397238ed071c81f514f572013236b92d30d11ede8f99653f1b9",
          "sha256": "4e492d1b031c644c3fe7190f65dcb7af8ffa064069138bfbbba6896b86f811c7",
          "sha1": "95583df2a4e9add820c13616d5b5f9ebe452c65f",
          "md5": "99a147abd60083b95aea6c2587312e9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "4.8.9"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-core-bom",
          "version": {
            "requires": "4.8.9"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "micronaut-json-schema-common-1.5.1-SNAPSHOT.jar",
          "url": "micronaut-json-schema-common-1.5.1-SNAPSHOT.jar",
          "size": 16417,
          "sha512": "64c3278bcaad8ede86bb75163b64434352085e3d9df647f5dfcf2c873ef53474a8a4158fabc89397238ed071c81f514f572013236b92d30d11ede8f99653f1b9",
          "sha256": "4e492d1b031c644c3fe7190f65dcb7af8ffa064069138bfbbba6896b86f811c7",
          "sha1": "95583df2a4e9add820c13616d5b5f9ebe452c65f",
          "md5": "99a147abd60083b95aea6c2587312e9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "micronaut-json-schema-common-1.5.1-SNAPSHOT-sources.jar",
          "url": "micronaut-json-schema-common-1.5.1-SNAPSHOT-sources.jar",
          "size": 7924,
          "sha512": "965d034aa2c315b0e29ad2878e7ddf321db5735c28a6afc6bda96f97d6e7f591caa9cf8fabd40f646eb1ae43cdeef1f352c79fc418485147738672a05a1960d0",
          "sha256": "2c4cefa5a3b982358f82fbdfe5d655ed3bb61955f52388a3e3997ffb7e0f6d9a",
          "sha1": "d2bea928aa61967642f176821333539bcb0fb7dd",
          "md5": "c9b3e44cb3ab3e2c539b81f9d6e9f979"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "micronaut-json-schema-common-1.5.1-SNAPSHOT-javadoc.jar",
          "url": "micronaut-json-schema-common-1.5.1-SNAPSHOT-javadoc.jar",
          "size": 108058,
          "sha512": "b5dfd3a37ec1936888ec1b0c1561373267563959a705d1d569068e6b00d00866976c90867d7b5a2456c4ad737cbfcddb31837639d275205c874fcf950165b33d",
          "sha256": "0297337d415cf44be9ceaec6fdf4dd82c27d5e7f0a8160fa0f3f9d9cc353b65e",
          "sha1": "f9ce476c4049cec453ff79b43c17483a9ff70d16",
          "md5": "588dce10cb77a513470d6953f9cf9f3d"
        }
      ]
    }
  ]
}
