File log = new File(basedir, 'build.log')
assert log.exists()
assert log.text.contains(":aot-jar")
assert log.text.contains(":aot-run")
assert log.text.contains("BUILD SUCCESS")
assert log.text.contains("Hi!")
assert log.text.contains("Running with AOT optimizations")
