=== Using Micronaut AOT

*WARNING*: The Micronaut AOT module is in experimental stages. Use at your own risk!

:toc:

https://micronaut-projects.github.io/micronaut-aot/latest/guide/[Micronaut AOT] is a module which aims at pre-computing
a number of things at _build time_ in order to provide faster startup times and smaller binaries. At the moment, it
supports optimizing Micronaut applications only (Micronaut libraries or functions will be supported in a future release).

To enable Micronaut AOT, simply set the property `micronaut.aot.enabled`, either in the POM or via the command-line:

----
$ mvn package -Dmicronaut.aot.enabled=true
----

That integrated path continues to work through `micronaut-maven-plugin` on `5.0.x`, including the existing packaging and
`mn:run` flows.

==== Standalone AOT plugin

If a module only needs Micronaut AOT support, it can use the standalone `micronaut-maven-aot-plugin` without applying
the main Micronaut Maven plugin:

[source,xml]
----
  <build>
    <plugins>
      <plugin>
        <groupId>io.micronaut.maven</groupId>
        <artifactId>micronaut-maven-aot-plugin</artifactId>
        <version>{site-version}</version>
        <executions>
          <execution>
            <goals>
              <goal>aot-analysis</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
----

The standalone plugin keeps the same goals, but it uses the `mn-aot` prefix for direct invocation:

----
$ mvn mn-aot:aot-sample-config -Dmicronaut.aot.enabled=true
----

When both plugins are declared in the same build, `micronaut-maven-plugin` remains the owner of integrated AOT
execution and the standalone `aot-analysis` goal will skip itself to avoid double-running AOT.

When Micronaut AOT is enabled, the packaged (or exploded) format of the application will contain some optimizations
computed at build time. It may contain, for example, additional classes, or even have different resources.

*IMPORTANT*: Micronaut AOT is a deployment optimization: it adds to build time, in order to make the final application
faster to start, or the native images smaller. Therefore, if you use the AOT tasks during development, your feedback
cycle will be slower (but the application will start faster). It is a good idea, however, to check the result of the
optimization locally, similarly to what you’d do for a native image.

Currently, Micronaut AOT supports 2 runtimes: `jit` (the default) and `native`. To change it, use the
`micronaut.aot.runtime` property. Note that if your `packaging` and `micronaut.aot.runtime` properties don't match,
the plugin will issue a warning in the build log:

----
$ mvn package -Dmicronaut.aot.enabled=true -Dpackaging=native-image

[INFO] --- mn:4.0.0:aot-sample-config (default-cli) @ demo ---
[WARNING] Packaging is set to [native-image], but Micronaut AOT runtime is set to [jit]. Please change them so that they match
----

==== Defining additional AOT dependencies

It is possible to add additional dependencies to the AOT execution classpath that may be required by some optimizations,
or to include an external AOT optimizer (in the future, some modules such as `micronaut-security` may offer additional
optimizers that can be used).

For example, the `logback.xml.to.java` optimization requires additional dependencies that can be defined in your POM
as follows:

[source,xml]
----
  <build>
    <plugins>
      <plugin>
        <groupId>io.micronaut.maven</groupId>
        <artifactId>micronaut-maven-plugin</artifactId>
        <configuration>
          <aotDependencies>
            <dependency>
              <groupId>ch.qos.logback</groupId>
              <artifactId>logback-classic</artifactId>
              <version>1.4.5</version>
            </dependency>
            <dependency>
              <groupId>org.fusesource.jansi</groupId>
              <artifactId>jansi</artifactId>
              <version>2.4.0</version>
            </dependency>
          </aotDependencies>
        </configuration>
      </plugin>
    </plugins>
  </build>
----

==== Configuration

Micronaut AOT can be configured with a `.properties` file. To get started with the possible options and their
description, run the `aot-sample-config` goal:

----
$ mvn -Dmicronaut.aot.enabled mn:aot-sample-config

[INFO] ...
[INFO] Executing Micronaut AOT analysis
[INFO] Sample configuration file written to /my-app/target/aot/jit/aot.properties
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
----

Then, copy the `target/aot/jit/aot.properties` to your root directory, and adapt it to your needs. If using a different
directory, use the `micronaut.aot.config` property to specify its location.

For a full list of configuration options, check the link:../aot-analysis-mojo.html[`aot-analysis` goal documentation].

==== Excluding dependencies

If you want to exclude a dependency from AOT processing, use the `aotExclusions` configuration property.
For example, to exclude `com.example:example` use the following configuration:

[source,xml]
----
  <build>
    <plugins>
      <plugin>
        <groupId>io.micronaut.maven</groupId>
        <artifactId>micronaut-maven-plugin</artifactId>
        <configuration>
          <aotExclusions>
            <exclusion>
              <groupId>com.example</groupId>
              <artifactId>example</artifactId>
            </exclusion>
          </aotExclusions>
        </configuration>
      </plugin>
    </plugins>
  </build>
----

NOTE: It is recommended to add AOT exclusions if you are building native image and have
exclusions in the `native-maven-plugin`.
