micronaut:
  application:
    name: test-resources-disabled
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    driverClassName: org.postgresql.Driver
    schema-generate: CREATE
    dialect: POSTGRES
