{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.jsonschema",
    "module": "micronaut-json-schema-generator",
    "version": "1.5.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "4.8.9"
          }
        },
        {
          "group": "io.micronaut.jsonschema",
          "module": "micronaut-json-schema-annotations",
          "version": {
            "requires": "1.5.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.jsonschema",
          "module": "micronaut-json-schema-common",
          "version": {
            "requires": "1.5.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "micronaut-json-schema-generator-1.5.1-SNAPSHOT.jar",
          "url": "micronaut-json-schema-generator-1.5.1-SNAPSHOT.jar",
          "size": 51898,
          "sha512": "ce5b38971901668891b771b075b9cf6285221ea367e596027ac3e146dbb8cb8454d2d85439ff96c3bd2c0ea66dd9677ed51c09f06d865c519575ae95f2c0575e",
          "sha256": "ce2567adac22ab2eee5df26df47410d0e8b22cc33d6c2e15b97bafbbabab128f",
          "sha1": "49694c055211da25dd890981c7dbc273092d4037",
          "md5": "e67b831933eeb84012494b2baf94827b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.micronaut.sourcegen",
          "module": "micronaut-sourcegen-model",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "io.micronaut.sourcegen",
          "module": "micronaut-sourcegen-generator",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "io.micronaut.sourcegen",
          "module": "micronaut-sourcegen-generator-java",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "io.micronaut.sourcegen",
          "module": "micronaut-sourcegen-annotations",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "4.8.9"
          }
        },
        {
          "group": "io.micronaut.jsonschema",
          "module": "micronaut-json-schema-annotations",
          "version": {
            "requires": "1.5.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.jsonschema",
          "module": "micronaut-json-schema-common",
          "version": {
            "requires": "1.5.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-core-bom",
          "version": {
            "requires": "4.8.9"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "micronaut-json-schema-generator-1.5.1-SNAPSHOT.jar",
          "url": "micronaut-json-schema-generator-1.5.1-SNAPSHOT.jar",
          "size": 51898,
          "sha512": "ce5b38971901668891b771b075b9cf6285221ea367e596027ac3e146dbb8cb8454d2d85439ff96c3bd2c0ea66dd9677ed51c09f06d865c519575ae95f2c0575e",
          "sha256": "ce2567adac22ab2eee5df26df47410d0e8b22cc33d6c2e15b97bafbbabab128f",
          "sha1": "49694c055211da25dd890981c7dbc273092d4037",
          "md5": "e67b831933eeb84012494b2baf94827b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "micronaut-json-schema-generator-1.5.1-SNAPSHOT-sources.jar",
          "url": "micronaut-json-schema-generator-1.5.1-SNAPSHOT-sources.jar",
          "size": 29829,
          "sha512": "b717a416b7bff6ca20a69c5d024856b7aec28bb5033eea2537754701698159687d11b6ea1cfdcbaa3b0b7770c71ee4810e60567e236f5856db6adcdf10d57582",
          "sha256": "b3197d7a3fee4977f1797c655976e153ce28e7aeb374f4aa62de59660acceb30",
          "sha1": "cd6dba5fa7a2bf883ff645e12fd524b72c9ef0b0",
          "md5": "a52446c43d38c6bd4154f17a5bf786b4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "micronaut-json-schema-generator-1.5.1-SNAPSHOT-javadoc.jar",
          "url": "micronaut-json-schema-generator-1.5.1-SNAPSHOT-javadoc.jar",
          "size": 150423,
          "sha512": "2171fcb41426a79feaad2267f43077f8711c496f10a2dfd401cd8effef0387e053055bb2e643f627945a33ceae13f65ee29a432c6797af2471b1bbd7740201c5",
          "sha256": "bab25eb1c6a101d74efd1e4bb6cd4ba795f1299d7ca81e57dd3683cb8c0615f0",
          "sha1": "02a11355edf3b1719b62f360b300c5f622125a07",
          "md5": "70dbcb8272496ee830db5d5b8fb27284"
        }
      ]
    }
  ]
}
