#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Apr 01 14:12:34 EDT 2025
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1743531154587
maven-metadata-graalvm-native-build-tools-snapshots.xml.error=
maven-metadata-graalvm-native-build-tools-snapshots.xml.lastUpdated=1743531154592
maven-metadata-sonatype-snapshots.xml.lastUpdated=1743531154592
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1743531154591
