File log = new File(basedir, 'build.log')
assert log.exists()
assert log.text.contains("BUILD FAILURE")
assert log.text.contains("Kotlin OpenAPI client generation is not supported by the Micronaut Maven Plugin")
assert log.text.contains("Kotlin applications built with Maven are no longer supported in Micronaut Platform 5")
assert !log.text.contains("kotlin-maven-plugin")
