invoker.goals = -ntp package -Dpackaging=native-image -DskipNativeBuild=true -Dmicronaut.native-image.jib.enabled=true -Dmicronaut.native-image.jib.allow-platform-mismatch=true -DDOCKER_HOST=tcp://localhost:65432

invoker.os.family = !windows
