#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Apr 22 14:19:47 EDT 2025
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1745345987958
maven-metadata-graalvm-native-build-tools-snapshots.xml.error=
maven-metadata-graalvm-native-build-tools-snapshots.xml.lastUpdated=1745345987960
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1745345987959
