micronaut:
  application:
    name: test-resources-custom-dependency
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    driverClassName: org.postgresql.Driver
    schema-generate: CREATE_DROP
    dialect: POSTGRES
