File log = new File(basedir, 'build.log')
assert log.exists()
assert log.text.contains("BUILD FAILURE")
assert log.text.contains("io.micronaut.maven.enforcer.CheckSnakeYaml failed with message")
assert log.text.contains("YAML configuration file detected, but SnakeYAML is not on the runtime classpath. Make sure to add the following dependency:")
