invoker.goals = -ntp package -Dpackaging=native-image -Dmicronaut.native-image.jib.enabled=true -Djib.buildGoal=buildTar docker:build docker:start docker:stop docker:remove -Ddocker.removeMode=all

invoker.profiles = graalvm
invoker.os.family = !windows
