/*
 * Copyright 2017-2022 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.maven;

import io.micronaut.maven.core.DockerBuildStrategy;
import io.micronaut.maven.core.MicronautRuntime;
import io.micronaut.maven.core.MojoUtils;
import io.micronaut.maven.jdkaotcache.JdkAotCacheTraining;
import io.micronaut.maven.jdkaotcache.TrainingRun;
import io.micronaut.maven.jib.JibConfigurationService;
import io.micronaut.maven.jib.JibMicronautExtension;
import io.micronaut.maven.services.ApplicationConfigurationService;
import io.micronaut.maven.services.DockerService;
import io.micronaut.maven.services.ExecutorService;
import org.apache.maven.execution.MavenSession;
import org.apache.maven.plugin.MojoExecution;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Execute;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.MavenProject;
import org.apache.maven.shared.invoker.MavenInvocationException;
import org.graalvm.buildtools.utils.NativeImageUtils;

import javax.inject.Inject;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static io.micronaut.maven.DockerNativeMojo.ARGS_FILE_PROPERTY_NAME;

/**
 * <p>Generates a <code>Dockerfile</code> depending on the <code>packaging</code> and <code>micronaut.runtime</code>
 * properties.
 *
 * <pre>mvn mn:dockerfile -Dpackaging=docker-native -Dmicronaut.runtime=lambda</pre>
 *
 * @author Álvaro Sánchez-Mariscal
 * @since 1.1
 */
@Mojo(name = "dockerfile", requiresDependencyResolution = ResolutionScope.COMPILE_PLUS_RUNTIME)
@Execute(phase = LifecyclePhase.PROCESS_CLASSES)
public class DockerfileMojo extends AbstractDockerMojo {
    public static final String DOCKERFILE = "Dockerfile";
    public static final String DOCKERFILE_AWS_CUSTOM_RUNTIME = "DockerfileNativeLambda";
    public static final String DOCKERFILE_AWS = "DockerfileLambda";
    public static final String DOCKERFILE_ORACLE_CLOUD = "DockerfileOracleCloud";
    public static final String DOCKERFILE_NATIVE = "DockerfileNative";
    public static final String DOCKERFILE_CRAC = "DockerfileCrac";
    public static final String DOCKERFILE_CRAC_CHECKPOINT = "DockerfileCracCheckpoint";
    public static final String DOCKERFILE_CRAC_CHECKPOINT_FILE = "Dockerfile.crac.checkpoint";
    public static final String DOCKERFILE_NATIVE_DISTROLESS = "DockerfileNativeDistroless";
    public static final String DOCKERFILE_NATIVE_STATIC = "DockerfileNativeStatic";
    public static final String DOCKERFILE_NATIVE_ORACLE_CLOUD = "DockerfileNativeOracleCloud";
    public static final String NATIVE_BUILD_TOOLS_MAVEN_PLUGIN = "org.graalvm.buildtools:native-maven-plugin";
    static final String DOCKERFILE_JDK_AOT_CACHE = "DockerfileJdkAotCache";
    private static final String CLASS_NAME_PLACEHOLDER = "CLASS_NAME";
    private static final String JDK_AOT_CACHE_TRAINING_PLACEHOLDER = "JDK_AOT_CACHE_TRAINING";
    private static final String EXEC_MAIN_CLASS_SOURCE = "exec.mainClass";
    /**
     * Where the training script writes the JDK AOT cache. The {@code ENTRYPOINT} of the {@code DockerfileJdkAotCache}
     * template loads it from there.
     */
    private static final String JDK_AOT_CACHE_IMAGE_FILE = "/home/app/app.aot";

    private final ExecutorService executorService;
    private String jdkAotCacheTrainingArguments = "";

    /**
     * <p>
     * Whether to train a JDK AOT cache (JEP 483, Java 25 or later) for the application and start it with the cache,
     * which makes it start faster. The image runs the application once while it is built, in the mode that
     * {@code micronaut.docker.jdkAotCache.trainingMode} selects, and the image's own {@code java} writes the cache.
     * Only for {@code docker} packaging with the default runtime: with Jib, and in the {@code Dockerfile} generated by
     * {@code mn:dockerfile}.
     * </p>
     * <p>
     * Training needs a Docker daemon, also with {@code jib.buildGoal=buildTar} or {@code build}. With Jib, the image
     * is built for the daemon's platform only, and the Jib {@code container.jvmFlags} must select a garbage collector,
     * for example {@code -XX:+UseSerialGC}.
     * </p>
     *
     * @since 5.1.0
     */
    @Parameter(property = "micronaut.docker.jdkAotCache", defaultValue = "false")
    private boolean jdkAotCache;

    /**
     * <p>
     * What the application does in the JDK AOT cache training run ({@code micronaut.docker.jdkAotCache}):
     * </p>
     * <ul>
     *     <li>{@code load}: it reads its configuration, loads its bean definitions and the classes they name, creates
     *     no bean and exits. It does not start, so the training needs none of the services that its beans use, such
     *     as a database, which an image build does not have. It needs a Micronaut version with the
     *     {@code micronaut.application.training.mode} property.</li>
     *     <li>{@code start}: it starts, answers the requests of {@code micronaut.docker.jdkAotCache.trainingPaths}
     *     and is stopped. The cache is more complete, but every service that the application needs to start must be
     *     reachable from the image build.</li>
     * </ul>
     * <p>
     * When it is not set, the mode is {@code load} if the application's Micronaut version has it, and {@code start}
     * otherwise.
     * </p>
     *
     * @since 5.1.0
     */
    @Parameter(property = "micronaut.docker.jdkAotCache.trainingMode")
    private String jdkAotCacheTrainingMode;

    /**
     * <p>
     * The paths of the GET requests sent to the application during the JDK AOT cache training run
     * ({@code micronaut.docker.jdkAotCache}), once it is ready. A short, representative warm-up makes a better cache.
     * Only a training run that starts the application sends them: with the {@code load} training mode, setting them
     * fails the build.
     * </p>
     * <p>
     * A request that gets no response fails the build. So does a response status of 400 or more when the plugin sends
     * the requests, which it does on a Micronaut version without the training-run switch
     * ({@code micronaut.application.training.enabled}). With the switch, Micronaut sends them and its rule applies: a
     * status of 500 or more fails the build, and a status from 400 to 499 does not. Micronaut logs it as a warning
     * ({@code WARN}) in the output of the training run, and the build succeeds.
     * </p>
     *
     * @since 5.1.0
     */
    @Parameter(property = "micronaut.docker.jdkAotCache.trainingPaths")
    private List<String> jdkAotCacheTrainingPaths;

    /**
     * The timeout, in seconds, of each step of the JDK AOT cache training run ({@code micronaut.docker.jdkAotCache}):
     * waiting for the application to be ready, each warm-up request, and waiting for the application to exit and write
     * the cache. A {@code load} training run only has the last step.
     *
     * @since 5.1.0
     */
    @Parameter(property = "micronaut.docker.jdkAotCache.trainingTimeout", defaultValue = "180")
    private int jdkAotCacheTrainingTimeout;

    @Inject
    public DockerfileMojo(MavenProject mavenProject, DockerService dockerService, JibConfigurationService jibConfigurationService,
                          ApplicationConfigurationService applicationConfigurationService, ExecutorService executorService,
                          MavenSession mavenSession, MojoExecution mojoExecution) {
        super(mavenProject, jibConfigurationService, applicationConfigurationService, dockerService, mavenSession, mojoExecution);
        this.executorService = executorService;
    }

    @Override
    public void execute() throws MojoExecutionException {
        var runtime = MicronautRuntime.valueOf(micronautRuntime.toUpperCase());
        var packaging = Packaging.of(mavenProject.getPackaging());
        try {
            if (jdkAotCache && packaging != Packaging.DOCKER) {
                getLog().warn("micronaut.docker.jdkAotCache only applies to " + Packaging.DOCKER.id() + " packaging, ignoring it");
            }
            copyDependencies(jdkAotCache);
            var dockerfile = switch (packaging) {
                case DOCKER_NATIVE -> buildDockerfileNative(runtime);
                case DOCKER -> buildDockerfile(runtime);
                case DOCKER_CRAC -> buildCracDockerfile(runtime);
                default -> throw new MojoExecutionException("Packaging is set to [" + packaging + "]. To generate a Dockerfile, set the packaging to either [" + Packaging.DOCKER.id() + "] or [" + Packaging.DOCKER_NATIVE.id() + "]");
            };

            dockerfile.ifPresent(file -> getLog().info("Dockerfile written to: " + file.getAbsolutePath()));

        } catch (IOException | MavenInvocationException e) {
            throw new MojoExecutionException(e.getMessage(), e);
        }
    }

    private Optional<File> buildDockerfile(MicronautRuntime runtime) throws IOException, MojoExecutionException {
        if (jdkAotCache) {
            return buildJdkAotCacheDockerfile(runtime);
        }
        File dockerfile;
        switch (runtime.getBuildStrategy()) {
            case ORACLE_FUNCTION -> {
                dockerfile = dockerService.loadDockerfileAsResource(DOCKERFILE_ORACLE_CLOUD);
                oracleCloudFunctionCmd(dockerfile);
                processOracleFunctionDockerfile(dockerfile);
            }
            case LAMBDA -> {
                dockerfile = dockerService.loadDockerfileAsResource(DOCKERFILE_AWS);
                processDockerfile(dockerfile);
            }
            case DEFAULT -> {
                dockerfile = dockerService.loadDockerfileAsResource(DOCKERFILE);
                processDockerfile(dockerfile);
            }
            default -> throw new IllegalStateException("Unexpected value: " + runtime.getBuildStrategy());
        }
        return Optional.ofNullable(dockerfile);
    }

    private Optional<File> buildJdkAotCacheDockerfile(MicronautRuntime runtime) throws IOException, MojoExecutionException {
        if (runtime.getBuildStrategy() != DockerBuildStrategy.DEFAULT) {
            throw new MojoExecutionException("micronaut.docker.jdkAotCache only supports the default runtime, not "
                + micronautRuntime);
        }
        List<String> trainingPaths = JdkAotCacheTraining.validateTrainingPaths(jdkAotCacheTrainingPaths);
        TrainingRun trainingRun = TrainingRun.resolve(jdkAotCacheTrainingMode, trainingPaths, mavenProject.getArtifacts());
        trainingRun.logGeneratedDockerfileRun(getLog());
        jdkAotCacheTrainingArguments = jdkAotCacheTrainingArguments(trainingPaths, trainingRun);
        File dockerfile = dockerService.loadDockerfileAsResource(DOCKERFILE_JDK_AOT_CACHE);
        processDockerfile(dockerfile);
        return Optional.ofNullable(dockerfile);
    }

    private String jdkAotCacheTrainingArguments(List<String> trainingPaths, TrainingRun trainingRun) throws MojoExecutionException {
        if (jdkAotCacheTrainingTimeout <= 0) {
            throw new MojoExecutionException("micronaut.docker.jdkAotCache.trainingTimeout must be positive");
        }
        String port = validateExposedPorts("jib.container.ports", getPorts()).trim().split("[\\s/]+")[0];
        if (!trainingRun.usesSwitch() && port.isEmpty()) {
            throw new MojoExecutionException("micronaut.docker.jdkAotCache needs the HTTP port of the application to "
                + "warm it up. Set it with the Jib container.ports configuration.");
        }
        var arguments = new ArrayList<String>();
        arguments.add(JDK_AOT_CACHE_IMAGE_FILE);
        arguments.add(port.isEmpty() ? "0" : port);
        arguments.add(String.valueOf(jdkAotCacheTrainingTimeout));
        arguments.add(trainingRun.scriptArgument());
        for (String path : trainingPaths) {
            arguments.add(shellLiteral("micronaut.docker.jdkAotCache.trainingPaths", path));
        }
        return String.join(" ", arguments);
    }

    private Optional<File> buildCracDockerfile(MicronautRuntime runtime) throws IOException, MojoExecutionException {
        File dockerfile;
        switch (runtime.getBuildStrategy()) {
            case ORACLE_FUNCTION -> throw new MojoExecutionException("Oracle Functions are currently unsupported");
            case LAMBDA -> throw new MojoExecutionException("Lambda Functions are currently unsupported");
            case DEFAULT -> {
                dockerfile = dockerService.loadDockerfileAsResource(DOCKERFILE_CRAC_CHECKPOINT, DOCKERFILE_CRAC_CHECKPOINT_FILE);
                processDockerfile(dockerfile);
                dockerfile = dockerService.loadDockerfileAsResource(DOCKERFILE_CRAC);
                processDockerfile(dockerfile);
            }
            default -> throw new IllegalStateException("Unexpected value: " + runtime.getBuildStrategy());
        }
        return Optional.ofNullable(dockerfile);
    }

    static void processOracleFunctionDockerfile(File dockerfile) throws IOException {
        if (dockerfile != null) {
            var allLines = Files.readAllLines(dockerfile.toPath());
            String projectFnVersion = JibMicronautExtension.determineProjectFnVersion(System.getProperty("java.version"));
            allLines.add(0, allLines.remove(0) + projectFnVersion);
            String entrypoint = JibMicronautExtension.buildProjectFnEntrypoint()
                .stream()
                .map(s -> "\"" + s + "\"")
                .collect(Collectors.joining(", "));

            allLines.add("ENTRYPOINT [" + entrypoint + "]");

            Files.write(dockerfile.toPath(), allLines);
        }
    }

    private Optional<File> buildDockerfileNative(MicronautRuntime runtime) throws IOException, MavenInvocationException, MojoExecutionException {
        getLog().info("Generating GraalVM args file");
        executorService.invokeGoal(NATIVE_BUILD_TOOLS_MAVEN_PLUGIN, "write-args-file");
        File dockerfile;
        switch (runtime.getBuildStrategy()) {
            case LAMBDA -> {
                dockerfile = dockerService.loadDockerfileAsResource(DOCKERFILE_AWS_CUSTOM_RUNTIME);
                lambdaBootstrapCommand(dockerfile);
            }
            case ORACLE_FUNCTION -> {
                dockerfile = dockerService.loadDockerfileAsResource(DOCKERFILE_NATIVE_ORACLE_CLOUD);
                oracleCloudFunctionCmd(dockerfile);
            }
            case DEFAULT -> {
                String dockerfileName = DOCKERFILE_NATIVE;
                if (Boolean.TRUE.equals(staticNativeImage)) {
                    getLog().info("Generating a static native image");
                    dockerfileName = DockerfileMojo.DOCKERFILE_NATIVE_STATIC;
                } else if (baseImageRun.contains("distroless")) {
                    getLog().info("Generating a mostly static native image");
                    dockerfileName = DockerfileMojo.DOCKERFILE_NATIVE_DISTROLESS;
                }
                dockerfile = dockerService.loadDockerfileAsResource(dockerfileName);
            }
            default -> throw new IllegalStateException("Unexpected value: " + runtime.getBuildStrategy());
        }
        processDockerfile(dockerfile);
        return Optional.ofNullable(dockerfile);
    }

    private void processDockerfile(File dockerfile) throws IOException, MojoExecutionException {
        if (dockerfile == null) {
            return;
        }

        var allLines = Files.readAllLines(dockerfile.toPath());
        Files.write(dockerfile.toPath(), processDockerfileLines(allLines));

        String argsFile = findArgsFile();
        if (argsFile != null) {
            processNativeImageArgs(argsFile);
        }
    }

    private List<String> processDockerfileLines(List<String> allLines) throws MojoExecutionException {
        var result = new ArrayList<String>();
        for (String line : allLines) {
            String processedLine = processDockerfileLine(line);
            if (processedLine != null) {
                result.add(processedLine);
            }
        }
        return result;
    }

    private String processDockerfileLine(String line) throws MojoExecutionException {
        if (containsPlaceholder(line, JDK_AOT_CACHE_TRAINING_PLACEHOLDER)) {
            line = line.replace("${" + JDK_AOT_CACHE_TRAINING_PLACEHOLDER + "}", jdkAotCacheTrainingArguments);
        }
        if (line.startsWith("ARG")) {
            return shouldInlineArgLine(line) ? null : line;
        }
        if (containsPlaceholder(line, "BASE_IMAGE_RUN")) {
            return line.replace("${BASE_IMAGE_RUN}", validateImageReference("micronaut.native-image.base-image-run", baseImageRun));
        }
        if (containsPlaceholder(line, "BASE_IMAGE")) {
            return line.replace("${BASE_IMAGE}", validateImageReference("jib.from.image", getFrom()));
        }
        if (containsPlaceholder(line, "BASE_JAVA_IMAGE")) {
            return line.replace("${BASE_JAVA_IMAGE}", validateImageReference("base Java image", getBaseImage()));
        }
        if (containsPlaceholder(line, "GRAALVM_DOWNLOAD_URL")) {
            return line.replace("${GRAALVM_DOWNLOAD_URL}", shellLiteral("GraalVM download URL", validateDownloadUrl("GraalVM download URL", graalVmDownloadUrl())));
        }
        if (containsPlaceholder(line, CLASS_NAME_PLACEHOLDER)) {
            return replaceClassName(line);
        }
        if (containsPlaceholder(line, "PORTS")) {
            return line.replace("${PORTS}", validateExposedPorts("jib.container.ports", getPorts()));
        }
        return line;
    }

    private static boolean containsPlaceholder(String line, String placeholderName) {
        return line.contains("${" + placeholderName + "}");
    }

    private static boolean shouldInlineArgLine(String line) {
        String trimmed = line.trim();
        if (!trimmed.startsWith("ARG")) {
            return false;
        }
        String remainder = trimmed.substring(3).trim();
        if (remainder.isEmpty()) {
            return false;
        }

        int endEquals = remainder.indexOf('=');
        int endWhitespace = -1;
        for (int i = 0; i < remainder.length(); i++) {
            if (Character.isWhitespace(remainder.charAt(i))) {
                endWhitespace = i;
                break;
            }
        }

        int end = remainder.length();
        if (endEquals >= 0) {
            end = Math.min(end, endEquals);
        }
        if (endWhitespace >= 0) {
            end = Math.min(end, endWhitespace);
        }

        String argName = remainder.substring(0, end);
        return "BASE_IMAGE_RUN".equals(argName)
            || "BASE_JAVA_IMAGE".equals(argName)
            || "BASE_IMAGE".equals(argName)
            || "GRAALVM_DOWNLOAD_URL".equals(argName)
            || CLASS_NAME_PLACEHOLDER.equals(argName)
            || "PORTS".equals(argName);
    }

    private String replaceClassName(String line) throws MojoExecutionException {
        String className = isJsonArrayClassNameContext(line)
            ? escapeJsonString(EXEC_MAIN_CLASS_SOURCE, mainClass)
            : line.contains("\"${CLASS_NAME}\"")
                ? escapeShellDoubleQuoted(EXEC_MAIN_CLASS_SOURCE, mainClass)
            : shellLiteral(EXEC_MAIN_CLASS_SOURCE, mainClass);
        return line.replace("${CLASS_NAME}", className);
    }

    private static boolean isJsonArrayClassNameContext(String line) {
        return containsPlaceholder(line, CLASS_NAME_PLACEHOLDER)
            && (line.contains("ENTRYPOINT [") || line.contains("CMD ["));
    }

    private String findArgsFile() throws IOException {
        String argsFile = mavenProject.getProperties().getProperty(ARGS_FILE_PROPERTY_NAME);
        if (argsFile != null) {
            return argsFile;
        }
        Path targetPath = Paths.get(mavenProject.getBuild().getDirectory());
        try (Stream<Path> listStream = Files.list(targetPath)) {
            return listStream
                .filter(path -> {
                    String fileName = path.getFileName().toString();
                    return fileName.startsWith("native-image") && fileName.endsWith("args");
                })
                .findFirst()
                .map(path -> path.toAbsolutePath().toString())
                .orElse(null);
        }
    }

    private void processNativeImageArgs(String argsFile) throws IOException, MojoExecutionException {
        List<String> allNativeImageBuildArgs = MojoUtils.computeNativeImageArgs(nativeImageBuildArgs, baseImageRun, argsFile, supportsSharedArena());
        //Remove extra main class argument
        allNativeImageBuildArgs.remove(mainClass);
        getLog().info("GraalVM native image build args: " + allNativeImageBuildArgs);
        List<String> conversionResult = NativeImageUtils.convertToArgsFile(allNativeImageBuildArgs, Paths.get(mavenProject.getBuild().getDirectory()));
        if (conversionResult.size() == 1) {
            Files.delete(Paths.get(argsFile));
        }
    }
}
