FROM ubuntu:18.04

ARG CRAC_ARCH
ARG CRAC_JDK_VERSION
ARG CRAC_JDK_SHA256
ARG CRAC_JDK_URL
ARG CRAC_OS
WORKDIR /home/app

# Add required libraries
RUN apt-get update && apt-get install -y \
        curl \
        libnl-3-200 \
    && rm -rf /var/lib/apt/lists/*

# Install pinned CRaC OpenJDK
RUN echo Installing pinned CRaC OpenJDK $CRAC_JDK_VERSION for $CRAC_ARCH from $CRAC_JDK_URL
RUN name=$(basename "$CRAC_JDK_URL") \
    && echo "Downloading $name from $CRAC_JDK_URL" \
    && curl -fsSL "$CRAC_JDK_URL" -o "$name" \
    && echo "$CRAC_JDK_SHA256  $name" | sha256sum -c - \
    && tar xzf "$name" \
    && mv ${name%%.tar.gz} /azul-crac-jdk \
    && rm "$name"

# Copy layers
COPY classes /home/app/classes
COPY dependency/release/ /home/app/libs/release/
COPY dependency/snapshot/ /home/app/libs/snapshot/

# Add build scripts
COPY scripts/checkpoint.sh /home/app/checkpoint.sh
COPY scripts/warmup.sh /home/app/warmup.sh

ENTRYPOINT ["/home/app/checkpoint.sh"]
