File log = new File(basedir, 'build.log')
assert log.exists()
assert log.text.contains("Generating a static native image")
assert !log.text.contains("Using BASE_IMAGE_RUN")
assert log.text.contains("io.micronaut.runtime.Micronaut - Startup completed")