<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.micronaut.build.examples</groupId>
    <artifactId>test-resources-custom-reactor-dependency-parent</artifactId>
    <version>0.1</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>io.micronaut.platform</groupId>
        <artifactId>micronaut-parent</artifactId>
        <version>@it.micronaut.version@</version>
    </parent>

    <properties>
        <micronaut.version>@it.micronaut.version@</micronaut.version>
        <micronaut.runtime>netty</micronaut.runtime>
        <micronaut-maven-plugin.version>@project.version@</micronaut-maven-plugin.version>
        <micronaut.test.resources.version>@micronaut.test.resources.version@</micronaut.test.resources.version>
        <micronaut.testresources.version>${micronaut.test.resources.version}</micronaut.testresources.version>
        <micronaut.test.resources.enabled>true</micronaut.test.resources.enabled>
    </properties>

    <modules>
        <module>resolver</module>
        <module>app</module>
    </modules>
</project>
