File log = new File(basedir, 'build.log')
assert log.exists()
assert log.text.contains("Successfully tagged package-docker-crac-crac-checkpoint:latest")
assert log.text.contains("Successfully tagged alvarosanchez/package-docker-crac:0.1")
assert log.text.contains("[WARNING]  CRaC checkpoint files may contain sensitive information.")
assert log.text.contains("io.micronaut.runtime.Micronaut - Startup completed")