<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.micronaut.build.examples</groupId>
  <artifactId>openapi-generate-server-kotlin</artifactId>
  <version>0.1</version>
  <packaging>${packaging}</packaging>

  <parent>
    <groupId>io.micronaut.platform</groupId>
    <artifactId>micronaut-parent</artifactId>
    <version>@it.micronaut.version@</version>
  </parent>

  <properties>
    <micronaut.version>@it.micronaut.version@</micronaut.version>
    <micronaut-maven-plugin.version>@project.version@</micronaut-maven-plugin.version>
    <packaging>jar</packaging>
    <micronaut.runtime>netty</micronaut.runtime>
    <micronaut.openapi.definition>src/openapi/not-read-before-language-validation.json</micronaut.openapi.definition>
    <micronaut.openapi.lang>kotlin</micronaut.openapi.lang>
    <micronaut.openapi.generate.server>true</micronaut.openapi.generate.server>
    <maven.native.plugin.version>@native-maven-plugin.version@</maven.native.plugin.version>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>io.micronaut.maven</groupId>
        <artifactId>micronaut-maven-plugin</artifactId>
        <version>${micronaut-maven-plugin.version}</version>
      </plugin>
    </plugins>
  </build>
</project>
