micronaut:
  application:
    name: test-resources-run
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    schema-generate: CREATE
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
