micronaut:
  application:
    name: test-resources-run
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    schema-generate: CREATE
    dialect: MYSQL
#  users:
#    driverClassName: org.postgresql.Driver
#    schema-generate: CREATE_DROP
#    dialect: POSTGRES
