File log = new File(basedir, 'build.log')
assert log.exists()
assert log.text.contains("eclipse-temurin:${System.getProperty("java.specification.version")}-jre")
assert log.text.contains("[alvarosanchez/dockerfile-docker:0.1]: Built image")
assert log.text.contains("io.micronaut.runtime.Micronaut - Startup completed")