<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.micronaut.build.examples</groupId>
    <artifactId>configuration-validation-cache-invalidation</artifactId>
    <version>0.1</version>
    <packaging>${packaging}</packaging>

    <parent>
        <groupId>io.micronaut.platform</groupId>
        <artifactId>micronaut-parent</artifactId>
        <version>@it.micronaut.version@</version>
    </parent>

    <properties>
        <packaging>jar</packaging>
        <micronaut.version>@it.micronaut.version@</micronaut.version>
        <micronaut-maven-plugin.version>@project.version@</micronaut-maven-plugin.version>
        <maven.native.plugin.version>@native-maven-plugin.version@</maven.native.plugin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-runtime</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-http-server-netty</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.micronaut.maven</groupId>
                <artifactId>micronaut-maven-plugin</artifactId>
                <version>${micronaut-maven-plugin.version}</version>

                <executions>
                    <execution>
                        <id>validate-config-1</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>validate-configuration</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>validate-config-2</id>
                        <phase>package</phase>
                        <goals>
                            <goal>validate-configuration</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>mutate-main-resources</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <echo file="${project.basedir}/src/main/resources/cache-buster.txt" append="false">bumped</echo>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
