File log = new File(basedir, 'build.log')
assert log.exists()
assert log.text.contains("BUILD SUCCESS")
assert log.text.contains("Startup completed")
assert log.text.contains("Application1 running")
assert !log.text.contains("Application2 running")
assert !log.text.contains("Resource [logback.xml] occurs multiple times on the classpath")
assert log.text.contains("Embedded Application shutting down")
