name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      DEVELOCITY_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
      DEVELOCITY_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
    steps:
      - name: "🗑 Remove system JDKs"
        run: |
          sudo rm -rf /usr/lib/jvm/*
          unset JAVA_HOME
          export PATH=$(echo "$PATH" | tr ':' '\n' | grep -v '/usr/lib/jvm' | paste -sd:)

      - name: "📥 Checkout repository"
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: "🔐 Import GPG key"
        env:
          GPG_FILE: ${{ secrets.GPG_FILE }}
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "$GPG_FILE" | base64 -d | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: "☕️ Install Java and Maven and set up Apache Maven Central"
        uses: actions/setup-java@1d018f9b8b9b505bb578a83b230fabcce01af93b
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
          server-id: central
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD

      - name: "🟰 Set the current release version"
        id: release_version
        run: echo "release_version=${GITHUB_REF:11}" >> $GITHUB_OUTPUT

      - name: "🪾 Setup git"
        env:
          MICRONAUT_BUILD_EMAIL: ${{ secrets.MICRONAUT_BUILD_EMAIL }}
        run: |
          git config --global --add safe.directory /github/workspace
          git config --global user.email "$MICRONAUT_BUILD_EMAIL"
          git config --global user.name "micronaut-build"
          echo "Checking out ${{ github.event.release.target_commitish }}"
          git checkout ${{ github.event.release.target_commitish }}
          git tag -d v${{ steps.release_version.outputs.release_version }}
          git push origin :refs/tags/v${{ steps.release_version.outputs.release_version }}

      - name: "🔑 Setup SSH key"
        uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "❓ Figure out next version"
        id: next_version
        run: |
          chmod +x .github/scripts/increment_version.sh
          NV="$(.github/scripts/increment_version.sh -p "${{ steps.release_version.outputs.release_version }}")"
          echo "next_version=${NV}-SNAPSHOT" >> $GITHUB_OUTPUT

      - name: "⚙️ Prepare release"
        run: |
          ./mvnw --batch-mode release:prepare -DreleaseVersion=${{ steps.release_version.outputs.release_version }} -Dtag=v${{ steps.release_version.outputs.release_version }} -DdevelopmentVersion=${{ steps.next_version.outputs.next_version }} -Darguments="-Dinvoker.skip=true"
          cp -R target/site/apidocs/* micronaut-maven-plugin/target/site/apidocs

      - name: "📄 Publish docs to Github Pages"
        uses: micronaut-projects/github-pages-deploy-action@76d63aafbab7108d74e83be4e5b3b0501382e829
        env:
          BETA: ${{ contains(steps.release_version.outputs.release_version, 'M') || contains(steps.release_version.outputs.release_version, 'RC') }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: micronaut-maven-plugin/target/site
          VERSION: ${{ steps.release_version.outputs.release_version }}
          TARGET_REPOSITORY: ${{ github.repository }}

      - name: "📦 Perform release"
        run: ./mvnw --batch-mode release:perform -Darguments="-Dinvoker.skip=true"
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}

      - name: "🚪 Close release"
        if: success()
        run: |
          release_url=`cat $GITHUB_EVENT_PATH | jq '.release.url' | sed -e 's/^"\(.*\)"$/\1/g'`
          echo $release_url
          curl -s --request PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" $release_url --data "{\"draft\": false}"

      - name: "↩️ Rollback release"
        if: failure()
        run: ./mvnw release:rollback

      - name: "🚪 Close milestone ${{ steps.release_version.outputs.release_version }}"
        if: success()
        uses: Beakyn/gha-close-milestone@cb86f414f1601acbebdf9339f07ff7ac6ac0f24c
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          repository: ${{ github.repository }}
          milestone-title: ${{ steps.release_version.outputs.release_version }}
