name: Changelog

on:
  issues:
    types: [closed,reopened]
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'

jobs:
  release_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: micronaut-projects/github-actions/release-notes@master
        id: release_notes
      - uses: ncipollo/release-action@v1
        if: steps.release_notes.outputs.generated_changelog == 'true'
        with:
          allowUpdates: true
          commit: ${{ steps.release_notes.outputs.current_branch }}
          draft: true
          name: Micronaut Maven Plugin ${{ steps.release_notes.outputs.next_version }}
          tag: v${{ steps.release_notes.outputs.next_version }}
          bodyFile: CHANGELOG.md
          token: ${{ secrets.GH_TOKEN }}
