<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.micronaut.build.examples</groupId>
        <artifactId>test-resources-custom-reactor-dependency-parent</artifactId>
        <version>0.1</version>
    </parent>

    <artifactId>custom-reactor-resolver</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micronaut.testresources</groupId>
            <artifactId>micronaut-test-resources-core</artifactId>
            <version>${micronaut.test.resources.version}</version>
        </dependency>
    </dependencies>
</project>
